SiT_5sem_4lab/currency/urls.py
from django.urls import path

from currency import views

urlpatterns = [
    path('', views.convert_currency, name='convert_currency'),
]

SiT_5sem_4lab/django_currency_converter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('currency.urls')),
    path('admin/', admin.site.urls),
]

SiT_5sem_4lab/currency/models.py
from django.db import models

# Create your models here.

SiT_5sem_4lab/currency/forms.py
from django import forms

# dummy choices 
choices = INTEGER_CHOICES = [('', '')]


class CurrencyForm(forms.Form):
    source_currency_value = forms.DecimalField(label='Сумма')
    source_currency_code = forms.CharField(label='Из', widget=forms.Select(choices=INTEGER_CHOICES))
    target_currency_code = forms.CharField(label='В', widget=forms.Select(choices=INTEGER_CHOICES))

    def __init__(self, tuple_country_code, *args, **kwargs):
        # required to set the initial form drop down with choices
        self.tuple_country_code = tuple_country_code
        super(CurrencyForm, self).__init__(*args, **kwargs)

        self.fields['source_currency_code'].widget.choices = self.tuple_country_code
        self.fields['target_currency_code'].widget.choices = self.tuple_country_code

SiT_5sem_4lab/currency/views.py
from django.http import HttpResponse
from currency import forms
from django.shortcuts import render
import requests
import json


def convert_currency(request):
    """ Конвертируем с одной валюты в другую"""

    # апишка

    url = "https://api.apilayer.com/fixer/convert?to=to&from=from&amount=amount"

    payload = {}
    headers = {
        "apikey": "sppMDWVO5HwSfUXY7LMd1AshnKYM7aqG"
    }

    api_request = requests.request("GET", url, headers=headers, data=payload)
    currency_dict = json.loads(api_request.text)

    # currency_rates_dict = currency_dict['rates']
    currency_rates_dict = {}
    list_of_country_currency_code = [x for x in currency_rates_dict.keys()]
    tuple_of_country_codes = [tuple([x, x]) for x in list_of_country_currency_code]

    # инициализация формы
    currency_form = forms.CurrencyForm(tuple_of_country_codes, request.POST or None)

    converted_currency = ""
    if request.method == "POST":
        # проверка
        if currency_form.is_valid():
            # значения с html
            source_currency_code = currency_form.cleaned_data['source_currency_code']
            target_currency_code = currency_form.cleaned_data['target_currency_code']
            input_currency_value = currency_form.cleaned_data['source_currency_value']

            # Получаем текущее значение валюты 
            from_country_base_value = currency_rates_dict[source_currency_code]
            to_country_base_value = currency_rates_dict[target_currency_code]

            # Формула конвертации
            converted_currency = (to_country_base_value / from_country_base_value) * float(input_currency_value)

            return render(request, 'currency/currency-index.html',
                          {'currency_form': currency_form, 'converted_currency': f"{converted_currency:.2f}"})

    # Инициализация формы
    context = {
        'currency_form': currency_form,
        'converted_currency': converted_currency
    }
    return render(request, 'currency/currency-index.html', context)

SiT_5sem_4lab/currency/templates/currency/currency-index.html
<!doctype html>
<html lang="ru">
{% load static %}

{% load crispy_forms_tags %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
    <link href="{% static 'currency/css/base.css'%}" rel="stylesheet" type="text/css">

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script crossorigin="anonymous"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <title>Currency Converter</title>
</head>

<body class="d-flex m-auto justify-content-center"
      style="background: url('{% static 'currency/images/img.jpg' %}') 50% fixed; background-size: cover;">
<section style="width: 100%;">
    <div class="container" style="width: 100%;">
            <div class="card box-shadow m-2" style="width: 100%; min-height: 100%; min-width: 100%;">
                <div class="card-header text-center" style="width: 100%">
                    <h4>Конвертер валют </h4>
                </div>

                <form action="." class="p-3" enctype="multipart/form-data" id="form" method="POST" style="width: 100%">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ currency_form.source_currency_value|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ currency_form.source_currency_code|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ currency_form.target_currency_code|as_crispy_field }}
                        </div>
                    </div>
                    {% if converted_currency %}
                    <div class="card col-6 p-0 m-auto">
                        <div class="card-header text-center">
                            <h5>Итог</h5>
                            <h5>Из <b>{{currency_form.source_currency_code.value}}</b> в
                                <b>{{currency_form.target_currency_code.value}}</b></h5>
                        </div>
                        <div class="card-body">
                            {{converted_currency}}
                        </div>

                    </div>
                    {% endif %}


                    <hr class="hr-line-dashed">
                    <div class="form-footer text-center">
                        <input class="btn-danger btn-lg btn" id="submit" style="width: 100%" type="submit"
                               value="Конвертировать"/>
                    </div>

                </form>

            </div>
        </div>
</section>


</body>
<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            if($('#id_source_currency_value').val()){
                $('#submit').attr('value', 'Конвертируем...');

            }
        });
    });

</script>

</html>